apiVersion: batch/v1
kind: CronJob
metadata:
  name: ds-cron
spec:
  schedule: "*/45 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: snapshot
            image: bitnami/kubectl
            command: ["/opt/scripts/snapshot.sh"]
            # Args are optional  - $1 is the disk to snapshot, $2 is the pvc name to clone.
            # Defaults are:
            # args: ["data-ds-idrepo-0", "data-ds-idrepo-0-clone"]
            # IF YOU CHANGE THE SECOND PVC CLONE NAME - you must update the volumes: below
            # pod name is used to name the snapshot
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            volumeMounts:
            - name: scripts
              mountPath: /opt/scripts
          securityContext:
            fsGroup: 0
            runAsUser: 11111
          serviceAccount: ds-backup
          volumes:
          - name: scripts
            configMap:
              name: backup-scripts
              defaultMode: 0755