apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
  labels:
    tier: ds
    app: ds
spec:
  selector:
    matchLabels:
      app: ds
  serviceName: ds
  replicas: 1
  template:
    metadata:
      labels:
        tier: ds
    spec:
      # topologySpreadConstraints:
      # - maxSkew: 1
      #   topologyKey: topology.kubernetes.io/zone
      #   whenUnsatisfiable: DoNotSchedule
      #   labelSelector:
      #     matchLabels:
      #       app: ds
      initContainers:
      - name: initialize
        image: ds
        imagePullPolicy: IfNotPresent
        args: ["init"]
        volumeMounts:
        - name: data
          mountPath: /opt/opendj/data
        - name: passwords
          mountPath: /var/run/secrets/opendj-passwords
        # These are not required at runtime because the init entrypoint script sets up all the
        # keys in /var/run/secrets/keys.
        # When DS can directly consume the cert-manager secrets, these can be reenabled.
        # - name: ds-ssl-keypair
        #   mountPath: /var/run/secrets/ds-ssl-keypair
        # - name: ds-ssl-keypair
        #   mountPath: /var/run/secrets/truststore
        # - name: ds-master-keypair
        #   mountPath: /var/run/secrets/ds-master-keypair
        - name: keys
          mountPath: /var/run/secrets/keys
        env:
        - name: DS_SET_UID_ADMIN_AND_MONITOR_PASSWORDS
          value: "true"
        - name: DS_UID_MONITOR_PASSWORD_FILE
          value: "/var/run/secrets/opendj-passwords/monitor.pw"
        - name: DS_UID_ADMIN_PASSWORD_FILE
          value: "/var/run/secrets/opendj-passwords/dirmanager.pw"
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1024Mi
      containers:
      - name: ds
        image: ds
        imagePullPolicy: IfNotPresent
        args: ["start-ds"]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
          - name: ldap
            containerPort: 1389
          - name: ldaps
            containerPort: 1636
          - name: admin
            containerPort: 4444
          - name: replication
            containerPort: 8989
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1024Mi
        volumeMounts:
        - name: data
          mountPath: /opt/opendj/data
        - name: passwords
          mountPath: /var/run/secrets/opendj-passwords
        # These are not required at runtime because the init entrypoint sets up all the
        # keys in /var/run/secrets/keys.
        # When DS can directly consume the cert-manager secrets, these can be reenabled.
        # - name: ds-ssl-keypair
        #   mountPath: /var/run/secrets/ds-ssl-keypair
        # - name: ds-master-keypair
        #   mountPath: /var/run/secrets/ds-master-keypair
        - name: keys
          mountPath: /var/run/secrets/keys
      securityContext:
        fsGroup: 0
        runAsUser: 11111
        runAsGroup: 0
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: passwords
        secret:
          secretName: ds-passwords
      - name: ds-master-keypair
        secret:
          secretName: ds-master-keypair
          defaultMode: 384
      - name: ds-ssl-keypair
        secret:
          secretName: ds-ssl-keypair
          defaultMode: 384
      # Where the ds keys will get copied to.
      - name: keys
        emptyDir: {}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      # Include below storageClass in overlay if wanting to use local SSD.
      # storageClassName: "local-storage"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
