commonLabels:
  app.kubernetes.io/name: ds
  app.kubernetes.io/instance: ds-idrepo
  app.kubernetes.io/component: directory
  app.kubernetes.io/part-of: forgerock
resources:
- ds-idrepo.yaml

configurations:
- kustomizeConfig.yaml