kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/component: ui
  app.kubernetes.io/instance: admin-ui
  app.kubernetes.io/name: admin-ui
  app.kubernetes.io/part-of: forgerock
  tier: ui
resources:
- deployment.yaml
- service.yaml
images:
- name: .*admin-ui.*
  newName: gcr.io/forgerock-io/platform-admin-ui/docker-build
  newTag: 7.2.0-postcommit-latest
