# Builds the docker images used by the ds-operator (and may also be used for vanilla forgeops)
# This is run by a trigger. To run manually, from the forgeops root directory:
# gcloud builds submit --project forgeops-public --config docker/ds/cloudbuild.yaml
steps:
  # This is the mutable docker image used by the newest ds-operator.
- name: 'gcr.io/cloud-builders/docker'
  dir: docker/ds/ds-new
  args: [ 'build',
    '-t', 'gcr.io/forgeops-public/ds:latest',
    '-t', 'gcr.io/forgeops-public/ds:7.3-dev',
    '-t', 'gcr.io/forgeops-public/ds:7.3.0',
    '-t', 'us-docker.pkg.dev/forgeops-public/images/ds:latest',
    '-t', 'us-docker.pkg.dev/forgeops-public/images/ds:7.3-dev',
    '-t', 'us-docker.pkg.dev/forgeops-public/images/ds:7.3.0',
    '-f', './Dockerfile', '.' ]
images: [
    'gcr.io/forgeops-public/ds:7.3-dev',
    'gcr.io/forgeops-public/ds:latest',
    'us-docker.pkg.dev/forgeops-public/images/ds:7.3-dev',
    'us-docker.pkg.dev/forgeops-public/images/ds:latest'
   ]
