# Skaffold used for testing and building the ds image.
# Run using  skaffold dev --port-forward
apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: ds
build:
  artifacts:
  - image: ds
    context: ds
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
deploy:
  kustomize:
    paths:
    - ds-new-k8s



