timeout: 300s
steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - clusters
      - get-credentials
      - eng-shared-1
      - '--region=us-east1'
    id: authenticate-eng-shared-1
    waitFor:
      - '-'
  - name: 'us-docker.pkg.dev/$PROJECT_ID/images/cloudbuild:latest'
    args:
      - '-c'
      - 'kubectl delete pods --field-selector status.phase=Failed -A'
      - '--ignore-not-found=true'
    id: delete-shutdown-pods-eng-shared-1
    waitFor:
      - authenticate-eng-shared-1
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - clusters
      - get-credentials
      - eng-shared-2
      - '--region=us-east1'
    id: authenticate-eng-shared-2
    waitFor:
      - delete-shutdown-pods-eng-shared-1
  - name: 'us-docker.pkg.dev/$PROJECT_ID/images/cloudbuild:latest'
    args:
      - '-c'
      - 'kubectl delete pods --field-selector status.phase=Failed -A'
      - '--ignore-not-found=true'
    id: delete-shutdown-pods-eng-shared-2
    waitFor:
      - authenticate-eng-shared-2
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - clusters
      - get-credentials
      - eng-shared-7-1
      - '--region=us-east1-b'
    id: authenticate-eng-shared-7-1
    waitFor:
      - delete-shutdown-pods-eng-shared-2
  - name: 'us-docker.pkg.dev/$PROJECT_ID/images/cloudbuild:latest'
    args:
      - '-c'
      - 'kubectl delete pods --field-selector status.phase=Failed -A'
      - '--ignore-not-found=true'
    id: delete-shutdown-pods-eng-shared-7-1
    waitFor:
      - authenticate-eng-shared-7-1
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - clusters
      - get-credentials
      - eng-shared-7-2
      - '--region=us-east1'
    id: authenticate-eng-shared-7-2
    waitFor:
      - delete-shutdown-pods-eng-shared-7-1
  - name: 'us-docker.pkg.dev/$PROJECT_ID/images/cloudbuild:latest'
    args:
      - '-c'
      - 'kubectl delete pods --field-selector status.phase=Failed -A'
      - '--ignore-not-found=true'
    id: delete-shutdown-pods-eng-shared-7-2
    waitFor:
      - authenticate-eng-shared-7-2
    entrypoint: bash
