commonLabels:
  app.kubernetes.io/name: ds
  app.kubernetes.io/instance: ds-cts
  app.kubernetes.io/component: directory
  app.kubernetes.io/part-of: forgerock
resources:
- ds-cts.yaml

configurations:
- kustomizeConfig.yaml