# Skaffold used to iterate on the the toolbox.
apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: toolbox
build:
  artifacts:
  - image: cdk-toolbox
    context: toolbox
deploy:
  kustomize:
    paths:
    - ../../kustomize/base/toolbox
profiles:
- name: git
  build:
    artifacts:
    - image: git-server
      context: git-server
  deploy:
    kustomize:
      paths: [ "../../kustomize/base/git-server"]