steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gcp-pruner:latest', '.']
  dir: 'etc/gke/pruner'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/gcp-pruner:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/images/gcp-pruner:latest', '.']
  dir: 'etc/gke/pruner'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-docker.pkg.dev/$PROJECT_ID/images/gcp-pruner:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - '--service-account=gcp-pruner@$PROJECT_ID.iam.gserviceaccount.com'
    - '--image=us-docker.pkg.dev/$PROJECT_ID/images/gcp-pruner:latest'
    - '--timeout=600'
    - '--platform=managed'
    - '--region=us-east4'
    - 'gcp-pruner'
images:
- 'gcr.io/$PROJECT_ID/gcp-pruner:latest'
- 'us-docker.pkg.dev/$PROJECT_ID/images/gcp-pruner:latest'
