timeout: 300s
steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - clusters
      - get-credentials
      - eng-shared-1
      - '--region=us-east1'
    id: authenticate-eng-shared-1
    waitFor:
      - '-'
  - name: 'us-docker.pkg.dev/$PROJECT_ID/images/cloudbuild:latest'
    entrypoint: bash
    id: slack-notify-eng-shared-1
    waitFor: ['authenticate-eng-shared-1']
    secretEnv: ['SLACK_WEBHOOK_URL', 'SLACK_FAILED_WEBHOOK_URL']
    args:
      - -c
      - |-
        ./cicd/bin/old-deploy-slack-notify "eng-shared-1"
  - name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - clusters
      - get-credentials
      - eng-shared-2
      - '--region=us-east1'
    id: authenticate-eng-shared-2
    waitFor: ['slack-notify-eng-shared-1']
  - name: 'us-docker.pkg.dev/$PROJECT_ID/images/cloudbuild:latest'
    entrypoint: bash
    id: slack-notify-eng-shared-2
    waitFor: ['authenticate-eng-shared-2']
    secretEnv: ['SLACK_WEBHOOK_URL', 'SLACK_FAILED_WEBHOOK_URL']
    args:
      - -c
      - |-
        ./cicd/bin/old-deploy-slack-notify "eng-shared-2"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/slack_webhook_url_old_deploy/versions/latest
      env: 'SLACK_WEBHOOK_URL'
    - versionName: projects/$PROJECT_NUMBER/secrets/slack_webhook_url_old_deploy_fail/versions/latest
      env: 'SLACK_FAILED_WEBHOOK_URL'
