# The claim for the backup storage volume. This must be large enough to host the ldif or ds backup
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: restored-ds-data
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
