apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  # Some optional settings
  # If you are using cert-manager and Let's Encrypt in your cluster and want real certs - set this
  # CERT_ISSUER: letsencrypt-prod
  AM_STORES_CTS_SERVERS: "ds-cts-0.ds-cts:1636,ds-cts-1.ds-cts:1636,ds-cts-2.ds-cts:1636"
  AM_STORES_USER_SERVERS: "ds-idrepo-0.ds-idrepo:1636,ds-idrepo-1.ds-idrepo:1636,ds-idrepo-2.ds-idrepo:1636"