# This is executed when any changes under docker/cli-tools are commited
timeout: 1200s
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: toolbox
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/toolbox', 'toolbox']
  dir: docker/cli-tools
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/repo', 'repo']
  dir: docker/cli-tools
  waitFor:
    - toolbox
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/git-server', 'git-server']
  dir: docker/cli-tools
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: toolbox-ar
  args: ['build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/images/toolbox', 'toolbox']
  dir: docker/cli-tools
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/images/repo', 'repo']
  dir: docker/cli-tools
  waitFor:
    - toolbox-ar
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/images/git-server', 'git-server']
  dir: docker/cli-tools
  waitFor: ['-']
images:
- gcr.io/$PROJECT_ID/toolbox
- gcr.io/$PROJECT_ID/repo
- gcr.io/$PROJECT_ID/git-server
- us-docker.pkg.dev/$PROJECT_ID/images/toolbox
- us-docker.pkg.dev/$PROJECT_ID/images/repo
- us-docker.pkg.dev/$PROJECT_ID/images/git-server
