timeout: 900s
options:
  env:
    - NAMESPACE=smoke
    - DEFAULT_DOCKER_REPO=us-docker.pkg.dev/engineering-devops/images

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: authenticate
  waitFor: ['-']
  args: ['container', 'clusters', 'get-credentials', 'eng-shared-2', '--region=us-east1']

- name: 'us-docker.pkg.dev/$PROJECT_ID/images/cloudbuild:latest'
  entrypoint: bash
  id: build-images
  waitFor: ['authenticate']
  args:
    - -c
    - |-
      ./bin/forgeops build am amster idm ds-idrepo --push-to $$DEFAULT_DOCKER_REPO

- name: 'us-docker.pkg.dev/$PROJECT_ID/images/cloudbuild:latest'
  entrypoint: bash
  id: nuke-environment
  waitFor: ['build-images']
  args:
    - -c
    - |-
      ./bin/forgeops delete -n $$NAMESPACE --yes

- name: 'us-docker.pkg.dev/$PROJECT_ID/images/cloudbuild:latest'
  entrypoint: bash
  id: deploy-cdk
  waitFor: ['nuke-environment']
  args:
    - -c
    - |-
      ./bin/forgeops install --fqdn smoke.eng.forgeops.com -n $$NAMESPACE

- name: 'us-docker.pkg.dev/$PROJECT_ID/images/cloudbuild:latest'
  entrypoint: bash
  id: smoke-tests
  waitFor: ['deploy-cdk']
  args:
    - -c
    - |-
      ./cicd/bin/smoke-tests
