apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/kustomizeConfig

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: platform-config
  data:
    AM_STORES_CTS_SERVERS: ds-idrepo-0.ds-idrepo:1636
    AM_STORES_USER_SERVERS: ds-idrepo-0.ds-idrepo:1636


