apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mini
  region: us-east-1
  version: "1.20"
  tags:
    forgerock.io/cluster: "cdm-mini"
    # ES_USEREMAIL: ${ES_USEREMAIL}
    # ES_ZONE: ${ES_ZONE}
    # ES_BUSINESSUNIT: ${ES_BUSINESSUNIT}
    # BILLING_ENTITY: ${BILLING_ENTITY}
    # ES_OWNEDBY: ${ES_OWNEDBY}
    # ES_MANAGEDBY: ${ES_MANAGEDBY}

vpc:
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
  #cidr: 192.168.0.0/16

availabilityZones: ["us-east-1a","us-east-1b","us-east-1c"]

nodeGroups:
  - name: primary
    instanceType: m5.xlarge
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 80
    iam:
      withAddonPolicies:
        autoScaler: true
        certManager: true
        ebs: true
    labels:
      frontend: "true"
      ds: "true"
      forgerock.io/cluster: "cdm-mini"
      forgerock.io/role: "primary"
    tags:
      forgerock.io/cluster: "cdm-mini"
      forgerock.io/role: "primary"
      # ES_USEREMAIL: ${ES_USEREMAIL}
      # ES_ZONE: ${ES_ZONE}
      # ES_BUSINESSUNIT: ${ES_BUSINESSUNIT}
      # BILLING_ENTITY: ${BILLING_ENTITY}
      # ES_OWNEDBY: ${ES_OWNEDBY}
      # ES_MANAGEDBY: ${ES_MANAGEDBY}
    privateNetworking: true
    ssh:
      # eksctl will use your default public key (e.a. $HOME/.ssh/id_rsa.pub) if no path is provided
      # publicKeyPath:
      allow: true
