# am-only profile used for PIT tests
resources:
  - ../../../base/kustomizeConfig
  - ../../../base/am
  - ../../../base/amster
  - ../../../base/ds/cts
  - ../../../base/ds/idrepo
  - ../../../base/ldif-importer
  - ingress.yaml

patches:
  - path: base.yaml
  - path: ds-idrepo-old.yaml
