timeout: 1500s
steps:
# clone all the things
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--all']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  env:
    - REPO=$_REPO
    - IMAGE_TAG=$TAG_NAME
  args:
    - '-c'
    - |-
      ./cicd/bin/docker-clone

- name: 'us-docker.pkg.dev/$PROJECT_ID/images/cloudbuild'
  entrypoint: bash
  env:
    - IMAGE_TAG=$TAG_NAME
    - PROFILE_NAME=$_PROFILE_NAME
    - REPO=$_REPO
  args:
    - '-c'
    - |-
      ./cicd/bin/build-image-tags

- name: 'us-docker.pkg.dev/$PROJECT_ID/images/repo'
  entrypoint: bash
  secretEnv:
    - 'GH_TOKEN'
  env:
    - DOCKER_REPO=us-docker.pkg.dev/forgeops-public/images
    - IMAGE_TAG=$TAG_NAME
  args:
    - '-c'
    - |-
      [[ $_CREATE_RELEASE == 1 ]] \
      && make -f docker/cli-tools/repo/Makefile release \
      || echo "Not creating release."

- name: 'us-docker.pkg.dev/$PROJECT_ID/images/cloudbuild'
  entrypoint: bash
  env:
    - IMAGE_TAG=$TAG_NAME
    - PROFILE_NAME=$_PROFILE_NAME
    - REPO=$_REPO
  args:
    - '-c'
    - |-
      ./cicd/bin/build-image-tags

- name: 'us-docker.pkg.dev/$PROJECT_ID/images/repo'
  entrypoint: bash
  secretEnv:
    - 'GH_TOKEN'
  env:
    - DOCKER_REPO=us-docker.pkg.dev/forgeops-public/images
    - IMAGE_TAG=$TAG_NAME
  args:
    - '-c'
    - |-
      [[ $_CREATE_RELEASE == 1 ]] \
      && make -f docker/cli-tools/repo/Makefile release \
      || echo "Not creating release."

availableSecrets:
  secretManager:
    - versionName: projects/1067706085367/secrets/GH_API_CLOUDBUILD/versions/latest
      env: 'GH_TOKEN'
