timeout: 1200s
options:
  env:
    - PROFILE_NAME=cdk
steps:
- name: 'us-docker.pkg.dev/$PROJECT_ID/images/skaffold:latest'
  entrypoint: bash
  secretEnv:
  - 'GIT_KEY'
  args:
    - -c
    - |-
      REPO=gcr.io/forgeops-public IMAGE_TAG=dev ./cicd/bin/build-image-tags
      REPO=gcr.io/forgeops-public IMAGE_TAG=latest ./cicd/bin/build-image-tags
      REPO=us-docker.pkg.dev/forgeops-public/images IMAGE_TAG=dev ./cicd/bin/build-image-tags
      REPO=us-docker.pkg.dev/forgeops-public/images IMAGE_TAG=latest ./cicd/bin/build-image-tags
availableSecrets:
  secretManager:
    - versionName: projects/427458503412/secrets/cloudbuild-platform-config-ssh-key/versions/latest
      env: 'GIT_KEY'
