#Patch DS CTS
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds-cts
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: ds
          resources:
            requests:
              memory: 3Gi
              cpu: 2000m
            limits:
              memory: 5Gi
      initContainers:
      - name: initialize
        resources:
          requests:
            memory: 3Gi
            cpu: 2000m
          limits:
            memory: 5Gi
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
      storageClassName: fast