apiVersion: v1
kind: Service
metadata:
  name: rcs-agent
spec:
  ports:
    - name: rcs-agent
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: rcs-agent
  type: ClusterIP
