apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: dev-utils
  files:
  - logback.xml
  - git-sync.sh
  - git-clone.sh
  - git-merge-all.sh
  - config-upgrader.sh
  - tar-config.sh

generatorOptions:
  disableNameSuffixHash: true
